### PR TITLE
Fix API inconsistencies and comments

### LINKED ISSUE #26: API inconsistencies
There are a couple of unnecessary API inconsistencies:
-  In a few places, such as [here](https://github.com/ovotech/kafka-serialization/blob/master/avro4s/src/main/scala/com/ovoenergy/kafka/serialization/avro4s/Avro4sSerialization.scala#L164-L174), a parameter named `includeFormatByte` is used.
-  In a few places, such as [here](https://github.com/ovotech/kafka-serialization/blob/master/avro4s/src/main/scala/com/ovoenergy/kafka/serialization/avro4s/Avro4sSerialization.scala#L82-L95), the equivalent parameter is named `includesFormatByte` instead.

I'm happy to raise a PR to correct this, if you tell me which of the two you'd like to standardise towards.

### PR DESCRIPTION
**Pull request by oliverlockwood**
Closes #26.

Note that I observed some typos in comments (serializers being referred to as deserializers) and fixed these while I was here.

### CODE REVIEW

**Comment by jocelyndrean** [comment]
Hi @oliverlockwood ! Thanks for your PR :)
It seems, we have to also update the tests. I guess this is here: https://github.com/ovotech/kafka-serialization/blob/master/avro4s/src/test/scala/com/ovoenergy/kafka/serialization/avro4s/Avro4sSerializationSpec.scala

**Comment by oliverlockwood** [comment]
@jocelyndrean my bad, I clearly hadn't had my coffee when I raised the PR this morning!  Tests and documentation now updated as well.

**Comment by filosganga** [comment]
As it introduces a non back compatibility change, I will increase the minor version as well. Will merge it this evening. Thanks for the PR

**Comment by filosganga** [comment]
Merged in #28

**Pull request closed without merging**
