### PR TITLE
Code changes to upgrade latest versions of kafka and confluent schema registry. 

### PR DESCRIPTION
**Pull request by jadireddi**
Upgraded to latest kafka major version and latest confluent schema registry to use the code:
https://github.com/confluentinc/schema-registry/pull/680
in the `JerseySchemaRegistryClient.scala`

### CODE REVIEW

**Comment by jadireddi** [comment]
Hi @filosganga ,
Made version update changes for Kafka and confluent schema registry, to use some of the features present in `confluent schema registry:4.1.1` library. For exp: https://github.com/confluentinc/schema-registry/pull/680 to register different aggregate event types with same `topic name`.
If you feel this PR add value, could you please review and merge the code changes.

**Comment by krish23** [comment]
@jadireddi any examples available

**Comment by filosganga** [comment]
@jadireddi I believe that while the schema registry will support multiple types per topic. The confluent serializer doesn't yet do it out of the box? Is it a correct assumption?

**Comment by jadireddi** [comment]
@filosganga , You are right. With the new feature , registering multiple schema's under same subject, developer's doesn't need to do any overhead while serializing and de-serializing. We just need to provide `subject name strategy` which serializing and de-serializing.   

For example :
 `val schemaRegistryEndpoint = "http://localhost:8081"

  val schemaRegisterProps: Map[String,String] = Map[String,String](
  "key.subject.name.strategy" → "io.confluent.kafka.serializers.subject.TopicRecordNameStrategy",
  "value.subject.name.strategy" → "io.confluent.kafka.serializers.subject.TopicRecordNameStrategy"
)
  val schemaRegistryClientSettings = new SchemaRegistryClientSettings (schemaRegistryEndpoint, com.ovoenergy.kafka.serialization.avro.SchemaRegistryClientSettings.DefaultAuthentication, 12, 4 )

  val schemaRegistryClient = JerseySchemaRegistryClient(schemaRegistryClientSettings)

  val serializer = avroBinarySchemaIdSerializer[UserCreated123](schemaRegistryClient, isKey = false, includesFormatByte = true,
    props = schemaRegisterProps)`

Above example `schemaRegisterProps` takes care. Please brief note, kindly refer:
https://www.confluent.io/blog/put-several-event-types-kafka-topic/

**Pull request merged**
